### ISSUE TITLE
API Doku falsch - loadpoint index

### ISSUE THREAD

**Issue by Waldmensch1** [evcc-io/docs#102]
hier https://docs.evcc.io/docs/reference/api#mqtt-api

steht
`Die MQTT API folgt der REST API Struktur, mit den Ladepunkt (loadpoint) IDs bei 0 beginnend:`

die loadpoint ID's beginnen allerdings im MQTT publisher bei 1

vgl mqtt.go zeile 137ff
```
		if p.LoadPoint != nil {
			id := *p.LoadPoint + 1
			topic = fmt.Sprintf("%s/loadpoints/%d", m.root, id)
		}
```

**Comment by premultiply** [comment]
Machst du einen PR für die notwenigen Doku-Änderungen hier? Danke!

**Comment by andig** [comment]
Ich denke auch- wir sollten hier lieber die Doku ändern als die Implementierung?

**Comment by Waldmensch1** [comment]
Ich habe mir das Doku repo geforked und würde einen PR machen, auch für die identifier Liste. Betrifft die id 0/1 Sache nur MQTT oder die REST Api auch?

**Comment by naltatis** [comment]
> Betrifft die id 0/1 Sache nur MQTT oder die REST Api auch?

Bei REST beginnt es mit `0`.
