### ISSUE TITLE
Netzbezug wenn PV DC-Leistung größer ist als AC-Leistung in Kombination mit DC-Speicher (Kostal)

### ISSUE THREAD

**Issue by Robbe64** [evcc-io/docs#108]
### Describe the bug

Habe einen Kostal Plenticore Wechselrichter mit DC-Speicher. Der Wechselrichter kann max. 10kW AC-Seitig ausgeben. Wird darüber hinaus von den Modulen mehr Strom erzeugt als der Wechselrichter AC-Seitig ausgeben kann UND ist der Speicher noch nicht geladen, so wird der überschüssige Strom direkt in den DC-Speicher geladen. (Einige Wandlungsverluste verpuffen)
Das führt nun offenbar dazu, dass EVCC beispielsweise eine PV-Leistung von 11,5 kW sieht aber eigentlich für Haus und Wallbox max. 10kW zur verfügung stehen. Damit kommt es dann zum Netzbezug und gelichzeitigem Laden des Speichers.
Ich hatte gedacht, dass evcc-io/evcc#3015 das Problem löst, das ist aber zumindest bei mir nicht der Fall.
![grafik](https://user-images.githubusercontent.com/6786232/165511051-0d6ea15d-ab99-4d95-b4c9-d3d1cefb7088.png)

### Steps to reproduce

Kann ich so allgemein nicht sagen. In meinem Fall:
- Viel Sonne, die zu deutlich mehr Generatorleistung führt als der Wechselrichter AC-Seitig ausgeben kann
- Speicher der noch nicht auf 100% ist
- Auto im PV Modus laden

### Configuration details

[evcc.yaml.txt](https://github.com/evcc-io/evcc/files/8571626/evcc.yaml.txt)

### Log details

[log.log](https://github.com/evcc-io/evcc/files/8571627/log.log)

### What type of operating system are you running?

Docker container

### Version

0.90 (1eed3044) (nightly mit der neuen UI)

**Comment by Robbe64** [comment]
Also muss ich in der Konfig unter site maxGridSupplyWhileBatteryCharging auf z.B. 50 Setzen?

**Comment by andig** [comment]
Genau. Mit dem Wert muss Du mal spielen, das ist die zulässige Regelbandbreite.
