### ISSUE TITLE
Document: Du musst gar keinen Zähler eintragen, der wird automatisch von der WB genommen!

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#127]
@7tobias Deine Alfen wird voll unterstützt. Du musst gar keinen Zähler eintragen, der wird automatisch von der WB genommen!

_Originally posted by @andig in https://github.com/evcc-io/evcc/discussions/3392#discussioncomment-2821998_

**Comment by VolkerK62** [comment]
@andig   mir ist nicht ganz klar, wo hier die Doku aktualisiert werden soll. In  https://docs.evcc.io/docs/reference/configuration/meters  ist der Umstand ganz klar beschrieben.

**Comment by andig** [comment]
Danke, dann erledigt 👍🏻
