### ISSUE TITLE
Standardwerte für enable / disable bei loadpoints

### ISSUE THREAD

**Issue by DanielGlaas** [evcc-io/docs#131]
Die Einstellungen für Aktivierung und Deaktivierung der Ladung via PV können über die Parameter [enable](https://docs.evcc.io/docs/reference/configuration/loadpoints/#enable) und [disable](https://docs.evcc.io/docs/reference/configuration/loadpoints/#disable) durchgeführt werden.

Bei beiden Werte gibt es jeweils `threshold` und `delay` als Unterwerte. Für diese sind keine Werte als Standard angegeben, was allerdings hilfreich wäre.

**Comment by premultiply** [comment]
Wichtig ist auch dass die entsprechenden Zeiteinheiten immer mit angeben werden! ;)

**Comment by andig** [comment]
> Für diese sind keine Werte als Standard angegeben, was allerdings hilfreich wäre.

Was meinst Du damit? Ich sehe hier jede Menge Defaults: https://github.com/evcc-io/evcc/blob/master/evcc.dist.yaml#L107

**Comment by DanielGlaas** [comment]
Also das ist die Ansicht für den Wert `enable.threshold`:
![enable_threshold](https://user-images.githubusercontent.com/58786395/170824258-24e3eb02-d6f1-46a5-93b6-d0a3d4005a25.PNG)
Unter `delay` für `enable` steht auch kein Standardwert
![enable_delay](https://user-images.githubusercontent.com/58786395/170824288-e09b6457-cfc1-40fe-90c6-74dd44516bc9.PNG)

Bei `disable` steht ein nicht passender Wert darunter. 
![disable_threshold](https://user-images.githubusercontent.com/58786395/170824381-85abb17e-97f8-4d4c-8542-43e22b4308c9.PNG)

> Ich sehe hier jede Menge Defaults: https://github.com/evcc-io/evcc/blob/master/evcc.dist.yaml#L107

Diese Werte sehe ich in der Doku nicht.

**Comment by DanielGlaas** [comment]
Wird diese Seite mit den Beschreibungen und Standardwerten etc. automatisch generiert oder manuell?
Mit einem entsprechendem Hinweis könnte ich versuchen, mich an dieser Stelle einzubringen.

**Comment by premultiply** [comment]
Sehr gerne. Diese Seite ist rein manuell. Nur die Seite(n) mit den Geräten werden automatisch aus den Templates erzeugt.

**Comment by DanielGlaas** [comment]
Ok, dann kann ich das ja mal versuchen, evtl. morgen Abend.

Ich clone mir diese Datei: https://github.com/evcc-io/docs/blob/main/docs/reference/configuration/loadpoints.md
und mache dann einen Pull-Request mit den Änderung. Ist das das korrekte Vorgehen?

**Comment by premultiply** [comment]
Auf gut Deutsch: Du kannst dir das ganze docs-Repository clonen, dann darin lustig rumeditieren und dann anschließend aus den ganzen commits einen PR formen. Das geht mit den entsprechenden git-Tools via Konsole, Anwendung oder z. B. auch in VSCode.

Oft wesentlich einfachere Alternative: Einfach in github (Webseite) die jeweilige Seite bzw. Datei bearbeiten (Symbol oben rechts) dann wird am Ende automatisch ein PR draus. Für die kleine Sachen und die Doku reicht das allemal. Da sind wir auch nicht so formalistisch wie im evcc-Quelltext.

**Comment by DanielGlaas** [comment]
Ok, alles klar. Ich nehme mir vor, es mal auszuprobieren.
