### ISSUE TITLE
Loadpoint phases wird bei automatischer Phasenumschaltung ignoriert

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#141]
@andig  Diesen Hinweis habe ich in der Doku nicht gefunden. Ich würde es entsprechend anpassen.
Eine technische Frage: Was ist mit Wallboxen, bei denen die Umschaltung nur mit Sponsortoken funktioniert. Wenn kein Token vorliegt, werden die behandelt wie normale Wallboxen und der Wert bei `phases` wird beachtet?

**Comment by premultiply** [comment]
> Wenn kein Token vorliegt, werden die behandelt wie normale Wallboxen und der Wert bei phases wird beachtet?

Ja, genau so ist es.
