### ISSUE TITLE
FAQ: evcc WebUI nicht erreichbar (im Demo-Modus funktioniert aber alles!!)

### ISSUE THREAD

**Issue by premultiply** [evcc-io/docs#157]
(evcc startet nicht)

Der Anwender hat üblicherweise nur den Service gestartet aber die auftretenden und reklamierten Konfigurationsfehler (im Log) nicht wahrgenommen.

Lösung: evcc erstmal auf der Konsole starten und Fehlermeldungen abarbeiten. Erst wenn das alles funktioniert dann den Service (wieder) starten.

**Comment by VolkerK62** [comment]
Ich werde das in die Doku einbauen. Allerdings kam mir eine Idee/Frage: Ist es möglich, bei einem fehlerhaften start/restart des service auf der Kommandozeile einen entsprechenden Hinweis auszugeben?
