### ISSUE TITLE
Offline-Fahrzeug als vehicle konfigurieren

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#177]
Da diese Frage öfter in den Diskussionen aufkommt, sollte ein entsprechendes Beispiel in die Doku aufgenommen werden,
KOmmt aus https://github.com/evcc-io/evcc/discussions/3072

**Comment by VolkerK62** [comment]
@andig  macht das jetzt noch Sinn in Zusammenhang mit dem Redesign der Fahrzeugerkennung?

**Comment by andig** [comment]
Mhhhm. Wenns später mal ein Ladelog gäbe vllt. schon- können wir ja offen lassen...

**Comment by VolkerK62** [comment]
ist eingerichtet worden
