### ISSUE TITLE
Document new apis

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#178]
https://github.com/evcc-io/evcc/pull/3721

**Comment by VolkerK62** [comment]
@premultiply  sorry für die unverschämte Frage ;-)   
Ist es richtig, dass bei den neuen REST API kein `site` dabei ist? (im Gegensatz zu MQTT)

**Comment by andig** [comment]
Nein... es steht nur nicht explizit dabei.

**Comment by premultiply** [comment]
Ich habe mich am Quellcode orientiert und da sehe ich zumindest keine Site:
https://github.com/evcc-io/evcc/blob/8bc7862fa3376a8e2e2969c5384efd23ba42cb8e/server/http.go#L44-L52

**Comment by andig** [comment]
Die markierten sind alle site, loadpoints kommen etwas weiter unten. Vielen Dank @premultiply !

**Comment by VolkerK62** [comment]
Wie muss man das aufrufen?   `api/residualpower` oder `api/site/residualpower`

**Comment by andig** [comment]
Genau so wies jetzt dokumentiert ist
