### ISSUE TITLE
Nachziehen der Lademodi

### ISSUE THREAD

**Issue by DanielGlaas** [evcc-io/docs#181]
In evcc in Version 0.96 gibt es die Modi

- Aus
- Min + PV
- PV
- Schnell
Siehe dieser Screenshot:
![Modus Schnell](https://user-images.githubusercontent.com/58786395/179484845-7e078828-9770-4976-872a-f1feaf54fe2f.png)

In der Doku steht aber "Schnell" nicht beschrieben, sondern "Sofort"
![Lademodi veraltet](https://user-images.githubusercontent.com/58786395/179484369-2c0b328a-5295-41aa-a26e-1146ffa2c591.png)

Leider habe ich in den Release Notes von evcc keinen Hinweis gefunden, wann und warum das geändert wurde:
https://github.com/evcc-io/evcc/releases
Ansonsten hätte ich mich selbst an einer Anpassung versucht.

**Comment by andig** [comment]
@naltatis in welcher Richtung wollen wir das fixen?

**Comment by naltatis** [comment]
Danke für die Anpassung!

Ja, ist im Zuge der Darkmode Umstellung reingekommen. Die Idee ist hier auf die Ladegeschwindigkeit (schnell) zu gehen und nicht auf das Ladeverhalten. Auch die Reihenfolge hat sich geändert (vorher Aus, Sofort, Min+PV, PV) nun von langsam nach schnell (Aus, Min+PV, PV, Sofort). Min+PV wird auf kurz oder lang aus der Moduswahl rausgenommen werden (siehe https://github.com/evcc-io/evcc/discussions/3530) und das Verhalten anderweitig auswählbar gemacht. Bis dahin würde ich aber PV und Min+PV auch noch mal tauschen, damit das mit der aufsteigenden Geschwindigkeit / Erwartete Energiemenge passt.
