### ISSUE TITLE
Document downgrades

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#183]
Danke schön. 
Kann man zwischenzeitlich auch ein downgrade auf zb 0.89 machen? Ist das irgendwo beschrieben wie man das macht?

Liebe Grüße 
Rainer Pieper

> Am 23.07.2022 um 19:18 schrieb andig ***@***.***>:
> 
> ﻿
> I‘ll close this here in favor of a direct support discussion. Let me know if I can help with anything.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

_Originally posted by @mergeli in https://github.com/evcc-io/evcc/issues/3927#issuecomment-1193262396_

**Comment by VolkerK62** [comment]
- Hier Release raussuchen: https://github.com/evcc-io/evcc/releases/tag/0.85
- runterladen: "wget https://github.com/evcc-io/evcc/releases/download/0.85/evcc_0.85_linux_arm64.tar.gz"
- entpacken: "tar xzfv evcc_0.85_linux_arm64.tar.gz"
- Service stoppen: "sudo systemctl stop evcc"
- ins entpackte Verzeichnis wechseln und kopieren: "sudo cp evcc /usr/bin/evcc"
- Service starten: "sudo systemctl start evcc"
