### ISSUE TITLE
Document Limit im Auto auf 100% setzen.

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#185]
Dann bitte das Limit im Auto auf 100% setzen.

_Originally posted by @premultiply in https://github.com/evcc-io/evcc/issues/3977#issuecomment-1198551409_

**Comment by naltatis** [comment]
Würde ich nicht als generelle Regel sehen. Bei mir steht das evcc Limit fast immer auf 100% und ich Regel das Limit über Auto/App. Das funktioniert zuverlässig(er) und ist ja auch der Weg wie ich das an fremden Ladepunkten mache.

Trotzdem sollten wir das natürlich dokumentieren. Gibt hier halt mehrere Wege mit dem Limit umzugehen.

**Comment by andig** [comment]
Wir sollten zumindest erklären, dass es keine Beziehung gibt und der Anwender sich der Dualität bewusst sein muss!
