### ISSUE TITLE
Document machineid + deviceid

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#186]

**Comment by VolkerK62** [comment]
https://github.com/evcc-io/evcc/discussions/3952#discussioncomment-3596104
@andig  ich vermute, dass ist das dazugehörige Issue. Da ich aber absolut nicht verstehe, worum es geht, kann ich hier leider nicht helfen.

**Comment by VolkerK62** [comment]
hab gerade gesehen ... das ist doppelt  #106

**Comment by andig** [comment]
Krasse Sache mit den Todos- danke für den Überblick!
