### ISSUE TITLE
Doku: Beschreibung der verwendeten "Variablen"

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#193]
[andig] commented (4021#issuecomment-1207384768)
    phases (writable): am Charger geschaltete Phasen.
    activePhases: vom Fahrzeug genutzte Phasen.
    phases1p3p: 1p3p Konfiguration, 0 für auto, 1/3 für fixed.

Könnte man sämliche verwendeten parameter/variablen/topics (wie immer man das nennt) in die Doku aufnehmen?
(Geht das "automatisch", analog zu templates?)
Das hilft beim verstehen von log-files und auch bei der Nutzung von influx.

**Comment by andig** [comment]
Siehe https://github.com/evcc-io/evcc/issues/4067#issuecomment-1207455508 für refactoring
