### ISSUE TITLE
Doku: Bedeutung min/maxcurrent bei automatischer Phasenumschaltung

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#196]
kommt aus https://github.com/evcc-io/evcc/discussions/4074

@andig @premultiply 
Ladung erfolgt 1p bis maxcurrent erreicht wird, dann wird auf 3p umgeschaltet
Ladung erfolgt 3p bis mincurrent erreicht wird, dann wird auf 1p umgeschaltet
Ist der Sachverhalt so richtig?

**Comment by andig** [comment]
Yep- Anzahl der Schaltvorgänge werden damit möglichst reduziert.
