### ISSUE TITLE
Doku: Möglicher Fehler bei Log Level

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#201]
Ist es möglich, dass `core` veraltet ist und jetzt `site` heißt?

Egal welchen level ich bei `core`benutze, es zeigt sich nciht im logfile.
Setze ich aber einen level bei `site`, dann werden die Meter-Werte angezeigt.

**Comment by andig** [comment]
Ja :O

**Comment by VolkerK62** [comment]
An die `evcc.dist.yaml` hab ich mich nicht herangewagt, die kann mann bestimmt nicht einfach so editieren, oder?

**Comment by premultiply** [comment]
Doch, im Prinzip genauso.
Nur halt im evcc-Repository.

Aber dort sind nur dann aussagekräftige Commit-Messages und PR-Titel wünschenswert.
Aber das schaffst du ;)

**Comment by VolkerK62** [comment]
Fängt ja schon damit an, dass ich damit "Nur halt im evcc-Repository" nix anfangen kann ;)
