### ISSUE TITLE
Dokumentation - Log, levels - Komponenten Fahrzeugname - veraltete Dokumentation?

### ISSUE THREAD

**Issue by stdt** [evcc-io/docs#208]
In der Dokumentation bei **log, levels** - **Mögliche Komponenten**  ist beim Unterpunkt _Fahrzeugname_ folgendes angegeben:

- _fahrzeugname_: Jedes definierte **vehicle** (Fahrzeug), hier ist der jeweilige Wert des Parameters **type** anzugeben.

https://docs.evcc.io/docs/reference/configuration/log

Ist das eine veraltete Information? 

Als **type** habe ich bei der Konfiguration in evcc.yaml **template** stehen (und bei **template: opel**).

Wie soll hier in der evcc.yaml also das log-level angegeben werden, wenn die Angabe in der Dokumentation unter https://docs.evcc.io/docs/reference/configuration/log nicht korrekt ist? 

So:

levels:  
 lp-1: debug  
 opel: debug

Oder so (unter Verwendung von **name**):

levels:  
 lp-1: debug  
 ev3: debug

Anbei der Auszug aus der evcc.yaml zum besseren Verständnis:

vehicles:
- type: template
  template: opel
  title: Mokka_e
  user: xxxxx@xxxxx.de
  password: 123456qwertz
  vin: VXKTRALALA0815
  capacity: 46
  name: ev3

**Comment by VolkerK62** [comment]
`template` ist ja nur eine Konfigurationserleichterung für den `type`.
Richtig ist in deinem Fall `opel: debug`
