### ISSUE TITLE
Raspi Pi : Anleitung für Installation des downloaded evcc file 

### ISSUE THREAD

**Issue by PV-Freak** [evcc-io/docs#225]
Zum Entpacken:
* Hier Release raussuchen: https://github.com/evcc-io/evcc/releases/tag/0.85
* runterladen: "wget https://github.com/evcc-io/evcc/releases/download/0.85/evcc_0.85_linux_arm64.tar.gz"
* entpacken: "tar xzfv evcc_0.85_linux_arm64.tar.gz"
* Service stoppen: "sudo systemctl stop evcc"
* ins entpackte Verzeichnis wechseln und kopieren: "sudo cp evcc /usr/bin/evcc"
* Service starten: "sudo systemctl start evcc"

Wenn Du aber jetzt mittels apt ein update machst wird es wieder überbügelt. Evtl müsstest Du dann lieber über apt selber machen:
* Verfügbare Versionen anzeigen: "sudo apt list -a evcc"
* bestimmte Version installieren: "sudo apt install evcc=0.85.1647312075"

Ich schreib das hier aus dem Kopf.. könnte also das ein oder andere ein klein wenig anders sein ;)

_Originally posted by @Sillium007 in https://github.com/evcc-io/evcc/discussions/2882#discussioncomment-2370249_

**Comment by Sillium007** [comment]
Wenn du ein kompatibles System hast ist es am einfachsten über apt. 
Ansonsten wie in der Anleitung beschrieben:
https://docs.evcc.io/docs/installation/manual/

Beim anderen Thread ging es ja um ein Downgrade.. Aber ja.. Upgrade würde auch entsprechend gehen. Halt am besten vorher ne Sicherung machen falls es nicht klappt.
Und die Änderungen beachten. Hab welche die eine Änderung an der Config erforderten.

**Comment by PV-Freak** [comment]
Hallo Sillium007
Vielen Dank für deine ausführliche Antwort.
Nun habe ich endlich gechecked, dass die „manuelle“ Installation unter deinem Link ja gut beschrieben ist. 
Auf die Schnelle habe ich in der evcc Anleitung auf der Suche nach der manuellen Installation immer nur WINDOWS gesehen und nicht den ganzen Text  „Manuell (inkl. Windows)“ gelesen 😅….
Beste Grüsse
PV-Freak
