### ISSUE TITLE
Doku CoarseCurrent

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#228]
>Lösung:
add
`features: ["coarsecurrent"]`
to the vehicle config.
/cc @VolkerK62

und was trägt man da ein? true/false?

_Originally posted by @VolkerK62 in https://github.com/evcc-io/evcc/issues/4662#issuecomment-1264203297_
 
Hintergrundinfo:
Problem: Fahrzeug (Tesla) kann nur in ganzen Ampere regeln; evcc "denkt" aber an entsprechenden Chargern, das Auto würde auch kleinen Änderungen folgen (was es nicht tut).
Ergebnis: bei wenigen mA Änderung von x,4 auf x,6 Ampere springt die Leistung um 1A mal Phasen. Die Steuerung fängt an zu takten.

**Comment by andig** [comment]
Features ist eine Liste von Strings, ich hab einfach die einzeilige Notation verwendet

**Comment by VolkerK62** [comment]
Bahnhof, Koffer weg .... ;-)   Du hast vergessen, dass ich kein Hacker bin ...

ich habe verstanden, dass das für die Kombination mA(mpere)-Wallbox und A(mpere)-Auto sinnvoll ist.

Muss man da als Anwender tätig werden?
Wenn ja, trägt man das in der Konfig beim vehicle ein?
Wenn ja, in welcher Form?

**Comment by andig** [comment]
Ok ;). Also ja/ja/genau wie es oben steht (deshalb hab ichs ja hingeschrieben!). Geht aber NICHT mit den Templates sondern nur wenn das Auto „von Hand“ konfiguriert ist (type: tesla). Wer an die Stelle kommt und verstanden hat, dass seine Regelung zappelt, der ist dann auch in der Lage das zu konfigurieren…
