### ISSUE TITLE
Solax Inverter Cloud

### ISSUE THREAD

**Issue by are0002** [evcc-io/docs#251]
Hi all,

When implementing template: solax-inverter-cloud I am getting always Power: 0W when my PV is having more than 1KWh. Is there maybe any parsing issue or something?

On the other hand I tried to use a custom http input but I am getting this error:

Get "https://www.solaxcloud.com/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=XXXXX&sn=XXXXXX": context deadline exceeded (Client.Timeout exceeded while awaiting headers).
Probably some issue regarding the Go HTTP client timeout config for some HTTP servers.

Regards

**Comment by premultiply** [comment]
This is the evcc docs repo.
Feel free to use the evcc repo discussions to ask your evcc related questions or use the issue tracker from the evcc repo.
