### ISSUE TITLE
Mercedes vehicle documentation

### ISSUE THREAD

**Issue by dm82m** [evcc-io/docs#253]
### Describe the bug

I found a merged PR for Mercedes vehicle but the official documentation is not telling anything about it. How can I configure my Mercedes within evcc? I can also contribute the documentation part if I am aware how the configuration is done.

### Steps to reproduce

-

### Configuration details

```yaml
-
```

### Log details

```text
-
```

### What type of operating system are you running?

Linux

**Comment by VolkerK62** [comment]
Anleitung für einen Mercedes Account  https://github.com/evcc-io/evcc/discussions/5738#discussioncomment-4753581
