### ISSUE TITLE
Doku: modbusproxy

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#274]
`modbusproxy` habe ich in der Doku nicht gefunden.
https://github.com/evcc-io/evcc/discussions/5094

Ich denke unter dem Punkt `Modbus` würde es nicht so gut passen, sondern eher unter `Referenz/evcc.yaml` als eigener Unterpunkt.
Leider weiss ich nicht, wie ich dort einen neuen Menüpunkt einfügen kann.

**Comment by andig** [comment]
Ich glaub Modbus wär gar nicht schlecht als Sonderthema- Modbus für Geräte die nur 1 Verbindung erlauben?

**Comment by VolkerK62** [comment]
ich habe auch überlegt. Passt thematisch natürlich dahin, ist aber auch eine eigenes item in der yaml.
Ich bau es dann in `Modbus` ein.

**Comment by VolkerK62** [comment]
ich habe es gerade mal ausprobiert. Lesen klappt, aber schreiben nicht. Kann man da nur lesen?

**Comment by VolkerK62** [comment]
hmm. ok.
Wenn man mehrere Geräte abgefragen möchte, dann für jedes Gerät einen eigenen `modbusproxy` Eintrag in der yaml?  
Immer mit `port: 5200`?

**Comment by andig** [comment]
Na die Ports und Zieladressen müssen schon stimmen- also jedes Ziel ein Eintrag
