### ISSUE TITLE
Wallbe Dokumentations Update erbeten

### ISSUE THREAD

**Issue by Hofyyy** [evcc-io/docs#28]
Seit Version 0.75 und neuen Wallbe Firmware Versionen ist der Eintrag NOTE soweit ich das sehe überholt.

Vielleicht könnte man hier folgenden schreiben:

Für eine bestmögliche Kompatibilität der Modbus TCP implementation wird
mindestens folgende Firmware empfohlen.
- Wallbe Eco 2.0 - SL-01.04.21
- Wallbe Pro - BE-03.01.04

Die Firmware Versionen können hier angefordert werden:
https://www.wallbe.de/firmware-updates/

**Comment by andig** [comment]
@premultiply ?

**Comment by premultiply** [comment]
Jaha. Morgen...

**Comment by Hofyyy** [comment]
Ich weiss nicht wie ihr das sehr, aber man sollte die Firmware zumindest offiziell nicht weitervertreilen und in der Doku lieber auf die Firma verweisen oder? Ich meine sonst muss man ja gefühlt die Box "supporten"...

**Comment by andig** [comment]
Muss ja niemand der keinen Sdm verwenden will. Das sollte klar werden.

**Comment by Hofyyy** [comment]
Die Doku liest sich ausgezeichnet.

Letzte Frage. Soll das legacy im config Beispiel noch drin bleiben auf der Dokuseite?

**Comment by premultiply** [comment]
Oh, das hab ich vor lauter Text glatt vergessen! Danke!

**Comment by Hofyyy** [comment]
Wenn ich schon noch keine Sourcecodeänderungen einbringe. So lese ich mindestens schon mal alles mit und gegen :-)

**Comment by premultiply** [comment]
Ich hoffe nur die Templates und das Frontend aktualisieren sich nun irgendwann richtig und ich habe nichts falsch gemacht... :)

**Comment by horstvogel** [comment]
Moin, jemand eine Idee wo ich für unsere Wallbe Pro mit EV Chargre Control RCM einen Firmware Download erhalte. Von Wallbe Compleo habe ich bisher noch keine Rückmeldung erhalten. Wir sind noch auf der Firmware Version 0,72, also sehr, sehr alt. Der Controler ist doch eigentlich von Phonenix? 
Vielen Dank!

**Comment by Hofyyy** [comment]
Die musst du hier per Email anfragen: mailto:wallbe-firmware@compleo-cs.com

**Comment by horstvogel** [comment]
Kurzes Update, Wallbe Compleo hat sich nicht gemeldet. Ich hätte das auch ehrlich gesagt nicht wirklich erwartet....anscheinend ist jetzt mit der Wallbox auch halbwegs ruhe, Wenn jetzt ein Update kommt von EVCC, dann starte ich nach dem Update einfach auch die Wallbox über die Weboberfläche vom Wallbox Controller neu. Vielleicht war das die "Lösung" 
Danke!

**Comment by premultiply** [comment]
Du kannst die Original-FW bei Phoenix einfach runterladen.
Welchen Controller hast du denn genau.
Mach mal bitte ein Bild von Innenleben deiner Box.

Ansonsten ist ja oben eine aktuellere Wallbe-Firmware für dich verlinkt.

**Comment by horstvogel** [comment]
Vielen, Dank für die Hilfe. 

Das ist die Wallbe pro Box. Die Zähler sind eine Besonderheit, die leider auch eher unschön sind. Wenn jemand einen Tipp hat, welche Original Modbus Zähler da 1zu1 gleich funktionieren würden, dann würde ich die auch gerne ersetzen. 


![image](https://github.com/evcc-io/docs/assets/25108737/4ded6365-5ada-44b0-9546-2270e6c27e33)

**Comment by premultiply** [comment]
Das sind die ganz normalen Phoenix-Controller wie sie auch in der Eco 2.0s drin sind. Nur halt mit uralter Firmware.
Das sind diese hier: https://www.phoenixcontact.com/de-de/produkte/ac-ladesteuerung-ev-cc-ac1-m3-cbc-rcm-eth-1018701
Dort gibt es auch die aktuelle Phoenix-Firmware. (Kann keine 0,1A-Schritte, nur 1A-Schritte)

Für die aktuelle Wallbe-Firmware (mit 0,1A-Schritten) melde dich mal im Slack-Kanal bei mir.

Wichtig: Vor dem Update die IP-Adresse immer auf Standard (zurück)stellen und am besten auch direkt mit dem Rechner dran.
Andernfalls ist das Update sehr hakelig weil sich zwischendrin die IP umstellt.

**Comment by horstvogel** [comment]
Nur zur Info:
die Firmware mit der Versionsnummer  SL.01,04,24 sind nur auf der Wallbe Pro drauf, leider ist 2 Tagen die Box wieder nicht erreichbar, weder über EVCC hier jetzt mit der Fehlermeldung EOF, vorher war die Meldung "charger: dial tcp ...connect: no route to host" 
und auch nicht über das Webinterface ist die Box wieder nicht erreichbar. 

Somit war die "alte" Firmware dann doch leider nicht das Problem. 

Muss ich mal schauen, was da dann das Problem vielleicht ist....

Vielen Dank nochmals für die Hilfe die man hier wirklich immer erhält!

**Comment by Hofyyy** [comment]
Hallo,

mal eine ganz doofe Idee. Hast du schon mal ein anderes Netzwerkkabel probiert, oder einen anderen Port? Eine statische IP?

Also ich habe auch die Wallbe Pro laufen mit der verlinkten Firmware. Und sie läuft wirklich komplett stabil.

daher die frage nach der Infrastruktur ...

**Comment by horstvogel** [comment]
Statische IP, 2 Controller auf 2 unterschiedlichen Ports...beide Wallboxen sind mal irgendwann nicht erreichbar. Kann mir noch keine Reim draus machen, warum.

**Comment by horstvogel** [comment]
Moin, gestern dann versucht die Wallbox über ein direkt an die Wallbox angeschlossenes Kabel zureichen. 
Einmal mit meiner jetzt eingestellten festen IP, also den PC auch in gleich Subnet.....dann einmal über die Wallbe default IP, PC dann auch ins default Subnet.... 
Auf beiden Wegen war die Wallbox nicht erreichbar. Somit würde ich vorsichtig das Netzwerk ausschließen und die Ladekontroller oder die Konfiguration eher  Problem Ursache in Verdacht haben. 

Dann einmal den Resetknopf kurz gedrückt, danach war die Wallbox wieder erreichbar, sowohl via Webinterface als auch über Modbus durch EVCC. Strom aus und Strom an sorgte nicht dafür, dass die Wallbe wieder erreichbar war. Das finde ich dann ganz seltsam

Habe dann einmal einen Werksresett durchgeführt, die aktuelle Firmware nochmals eingespielt und dann wieder ins Netzwerk via fester IP ...gebracht. Mal schauen, ob das dann jetzt läuft. Das erste Firmware Update auf SL-01.04.24 hatte geklappt, ohne das ich die default IP 192.168.0.8 gesetzt hatte, dieses wurde ja auch hier empfohlen. Mal schauen was dann jetzt so passiert.


Status der Wallbe Pro ohne das ein Auto angeschlossen ist. **Hier die Frage, Status ist wirklich Status? Oder kann/sollte man hier auch noch was einstellen??**

![image](https://github.com/evcc-io/docs/assets/25108737/d96a0f56-9ff3-48c9-aa5f-5e05f2b63ce4)


Die Konfiguration der Wallbe Pro, wie Sie bei mir eingestellt ist. Die Box hat **keinen** Zähler der via Modbus mit dem Controller kommuniziert. Der Zähler dient lediglich der Energieerfassung und hatte früher die Freigabe der Wallbox über den SmartMe Zähler über die Cloud der Firma eCarUp der Wallbox via potentialfreier Kontakte gesteuert. Die Zähler fliegen jetzt aber demnächst raus. 

![image](https://github.com/evcc-io/docs/assets/25108737/781fc263-8de7-48e5-87fb-5977f124fce4)




Danke!

**Comment by Hofyyy** [comment]
Hallo, dann drücken wir mal die Daumen. Verwirrt bin ich bei deiner Firmware. Bei mir steht bei der Wallbe Pro diese hier: Version: BE-03.01.29

**Comment by horstvogel** [comment]
> Hallo, dann drücken wir mal die Daumen. Verwirrt bin ich bei deiner Firmware. Bei mir steht bei der Wallbe Pro diese hier: Version: BE-03.01.29

Verwirrt bin ich zwischenzeitlich auch schon ;-) die BE-03.01.29 frisst die Wallbe Pro nicht, Sie bleibt immer im Firmware Uploadbereich hängen. mit der "falschen Firmware" SL-01.04.24   funktioniert das. Das einzige was noch nicht probiert wurde, ich das BE-xxxx Update mit dem Internet Explorer als Browser durchzuführen. Zum Glück hat ein Experte auf dem Notebook Windows 11 installiert, da gibt es dann kein Internet Explorer mehr drauf

Vielen Dank das Ihr mich hier unterstützt.

**Comment by csigristgit** [comment]
Ich habe aktuell dieselbe Problematik. Hat das mit dem Update auf die Version BE-xxx geklappt? Das ganze ist schon echt mühsam aufgebaut. Aktuell habe ich die 0.88, was ebenfalls Steinalt ist...

Grüsse

**Comment by daniell82** [comment]
Ich bin auf der Suche nach einer Wallbe Pro Firmware, Compleo habe ich angeschrieben auch wenn ich mir da keine Hoffnungen machen. Hat die Firmware einer von euch und kann mir die zusenden? Wäre echt mega, hab grad Probleme mit der offiziellen Firmware 2.27 und der Anbindung des Modbus Zählers...

**Comment by vannilla1** [comment]
Hello.

Hat jemand Erfahrung mit wallbe Pro Plus in Verbindung mit der eCarUp-Software? Ich würde gerne wissen, ob Sie Probleme haben, welche Firmware Sie haben usw., denn es gibt niemanden mehr von Wallbe oder eCarUp, der uns dabei helfen kann. Wir haben derzeit 46 defekte Punkte, die nicht mit der eCarUp-Software kommunizieren und selbst nach dem Anschließen der Station an den PC und dem Zurücksetzen wird die Verbindung nicht wiederhergestellt. Ich bin verzweifelt.

**Comment by naltatis** [comment]
@vannilla1 das hier ist unser Doku Repository. Würde dir empfehlen, die Frage in unseren Discussions im Hauptprojekt noch mal zu stellen. Da lesen viele Leute mit. https://github.com/evcc-io/evcc/discussions

**Comment by KoMa1978** [comment]
> kurz gedrückt, danach war die Wallbox wieder erreichbar, sowohl via Webinterface als auch über Modbus durch EVCC. Strom aus und Strom an sorgte nicht dafür, dass die Wallbe wieder

Hi,

passt vielleicht nicht ganz in den Thread, aber die Verbindungsprobleme kenne ich auch (mit der ECO 2.0s) ...
Das Problem tritt immer mal wieder auf ... eher unregelmäßig, gefühlt öfter, je wärmer es draußen wird.
Mach ich kurz den FI kurz aus und an, ist erstmal wieder alles OK
Das Problem kann man reproduzieren, wenn man den Deckel abnimmt und das gesteckte Netzwerkkabel bzw die Buchse in eine Richtung drückt.

Ich habe den LAN Port (Würth Electronik 74990101210) schonmal nachgelötet, bisher ohne Erfolg. Bin schon am überlegen, mir mal eine neue RJ45 Buchse zu bestellen. Ich vermute, der RJ45 Port hat eine Macke oder die Platine. Ich bin mir auch nicht sicher, ob da ein Magnetkontakt im Port ist, laut Beschreibung steht da was von Magnet und ohne Kabel kann ich mit dem Multimeter keinen Kontakt zwischen Lötstelle und Pin in der Buchse messen.

**Comment by Hofyyy** [comment]
Bin gerade auf Reise ...

**Comment by kuehnelfred-cyber** [comment]
Guten Abend, ich versuche 2 Wallbe Pro wieder fit zu machen. Die Firmwares die ich bisher probiert habe geben keine Ladewerte aus. Könntet ihr mir bitte die BF-01.04.24. schicken? Vielen Dank. @vannilla1 @premultiply @wiinf

**Comment by vannilla1** [comment]
> Guten Abend, ich versuche 2 Wallbe Pro wieder fit zu machen. Die Firmwares die ich bisher probiert habe geben keine Ladewerte aus. Könntet ihr mir bitte die BF-01.04.24. schicken? Vielen Dank. @vannilla1 @premultiply @wiinf 

Hallo. Ist die Firmware in ihrer aktuellen Form verfügbar?

**Comment by kuehnelfred-cyber** [comment]
Ich habe aktuell die Firmware BE-03.01.29 drauf. Da bekomme ich aber keine Verbrauchswerte an das Backend übertragen.
Ich hoffe daher, dass die  BF-01.04.24. mein Problem löst. Danke schon Mal

**Comment by Hofyyy** [comment]
Ich habe auch noch die BE-03.01.29 drauf, da läuft alles zauberhabt würde. Gibts für die BF-01.04.24 ein changelog? Sonst würde ich gerne auch beide installer haben. Habt Sie ausversehen gelöscht :-/ Kann sie dann auch dauerhaft public auf eine Nextcloud legen

**Comment by vannilla1** [comment]
> Ich habe aktuell die Firmware BE-03.01.29 drauf. Da bekomme ich aber keine Verbrauchswerte an das Backend übertragen. Ich hoffe daher, dass die BF-01.04.24. mein Problem löst. Danke schon Mal

Meiner Erfahrung nach ist ein Wechsel der Firmware nicht möglich. Wenn Sie beispielsweise die BE-Version haben, können Sie nicht auf die BF-Version wechseln. Diese Information stammt von ehemaligen Wallbe-Technikern. Es ist ein gewisses Maß an Übertaktung erforderlich. Ich betreibe 80 Wallbe Pro Plus-Ladestationen und habe dies an mehreren Geräten getestet. Ich könnte Ihnen auch die neueste BE- und BF-Firmware zur Verfügung stellen, aber wie bereits erwähnt, ist ein Wechsel nicht möglich. Sollte jedoch jemand Erfahrung damit haben und wissen, wie es geht, bitte ich um eine kurze Nachricht. Selbstverständlich kann ich Ihnen die Firmware – die jeweils neueste Version – zur Verfügung stellen, da es laut Compleo, die vor einigen Jahren von Wallbe übernommen wurde, keine neueren Versionen mehr geben wird. Ich bin übrigens Slowake und spreche kein Deutsch. Daher schreibe ich alles mit Google Translate. Ich bitte um Entschuldigung, falls etwas unverständlich ist.

**Comment by kuehnelfred-cyber** [comment]
Hallo Vannilla, danke für deine Nachricht. Ich hatte auch schon die Phoenix FW probiert. Aber leider auch keine Ladewerte an das Backend bekommen. Ich nehme gern die Firmware die du empfehlen kannst. Ich würde auch gern die BF-01.04.24 probieren. Vielleicht klappt das ja über den Umweg mit der Phoenix FW. 
Ich danke dir für deinen Support. Ich komme aus Deutschland und mein Englisch ist echt schlecht. 
Soll ich dir eine Nachricht über die hier hinterlegte Mail schreiben, dass du mir die FW schicken kannst?

**Comment by vannilla1** [comment]
> Hallo Vannilla, danke für deine Nachricht. Ich hatte auch schon die Phoenix FW probiert. Aber leider auch keine Ladewerte an das Backend bekommen. Ich nehme gern die Firmware die du empfehlen kannst. Ich würde auch gern die BF-01.04.24 probieren. Vielleicht klappt das ja über den Umweg mit der Phoenix FW. Ich danke dir für deinen Support. Ich komme aus Deutschland und mein Englisch ist echt schlecht. Soll ich dir eine Nachricht über die hier hinterlegte Mail schreiben, dass du mir die FW schicken kannst?

Ja, bitte senden Sie mir eine E-Mail. Ich werde Ihnen dann die Firmware zusenden. Falls Sie die Installation durchführen können, wäre ich Ihnen sehr dankbar, wenn Sie mir eine Anleitung zum Wechsel der Firmware von BE auf BF schicken könnten. Das wäre äußerst hilfreich.

**Comment by kuehnelfred-cyber** [comment]
Hab dir geschrieben. Natürlich schicke ich eine Anleitung durch wenn ich es schaffe. Danke dir.

**Comment by kuehnelfred-cyber** [comment]
@vannilla1 das Update auf die Firmware BF-01.04.24 hat ohne Probleme funktioniert. Jetzt bekomme ich auch endlich Zählerstände ins Backend. Vielen Dank nochmal.
Das direkte Update von der BE-03.01.29 habe ich durch eure Hinweise nicht probiert.
Ich bin von der BE-03.01.29 auf die 2.27 von Phoenix und habe dann erst BF-01.04.24 installiert.

Hier eine kurze Anleitung:
1. alle Einstellungen vor dem Wechsel zur Phoenix FW per Screenshot sichern, die sind sonst komplett verstellt. 
2. Die Phoenix FW organisieren. Gibt es beim Hersteller, Bitte dringend euer Modell checken. Ich bin über die Specs gegangen und habe mich dann für das Modell EV-CC-AC1-M3-RCM-ETH-3G-XP entschieden. Das kann aber auch voll nach hinten losgehen und ihr habt es geflashed. In diesem Fall bitte direkt per LAN Kabel über die Ursprungs IP den Zugriff probieren in der Hoffnung das der Bootloader noch angesprochen werden kann. Hier der Link und die Hinweise von goingelectric https://www.goingelectric.de/forum/viewtopic.php?t=83191&sid=fdca70b93cadd222f675864eb7fb87c7
3.  das PW ist entweder leer (keine Eingabe machen) oder Phoenix bitte erstmal leer probieren. Habe ich auch bloß durch probieren herausgefunden, Ist leider nicht viel dokumentiert.
4. Die FW BF-01.04.24 installieren und die zuvor per Screenshot gesicherten Werte überprüfen.

Das Ganze auf eigenes Risiko!

Viel Erfolg

Falls Jemand Empfehlungen für ein stabiles und kompatibles Backend hat würde ich mich freuen. Ich Teste aktuell über pump. Da gibt es aber ab und an Fehler beim Beenden des Ladevorgangs.

**Comment by vannilla1** [comment]
> das Update auf die Firmware BF-01.04.24 hat ohne Probleme funktioniert. Jetzt bekomme ich auch endlich Zählerstände ins Backend. Vielen Dank nochmal. Das direkte Update von der BE-03.01.29 habe ich durch eure Hinweise nicht probiert. Ich bin von der BE-03.01.29 auf die 2.27 von Phoenix und habe dann erst BF-01.04.24 installiert.
> 
> Hier eine kurze Anleitung:
> 
> 1. alle Einstellungen vor dem Wechsel zur Phoenix FW per Screenshot sichern, die sind sonst komplett verstellt.
> 2. Die Phoenix FW organisieren. Gibt es beim Hersteller, Bitte dringend euer Modell checken. Ich bin über die Specs gegangen und habe mich dann für das Modell EV-CC-AC1-M3-RCM-ETH-3G-XP entschieden. Das kann aber auch voll nach hinten losgehen und ihr habt es geflashed. In diesem Fall bitte direkt per LAN Kabel über die Ursprungs IP den Zugriff probieren in der Hoffnung das der Bootloader noch angesprochen werden kann. Hier der Link und die Hinweise von goingelectric https://www.goingelectric.de/forum/viewtopic.php?t=83191&sid=fdca70b93cadd222f675864eb7fb87c7
> 3. das PW ist entweder leer (keine Eingabe machen) oder Phoenix bitte erstmal leer probieren. Habe ich auch bloß durch probieren herausgefunden, Ist leider nicht viel dokumentiert.
> 4. Die FW BF-01.04.24 installieren und die zuvor per Screenshot gesicherten Werte überprüfen.
> 
> Das Ganze auf eigenes Risiko!
> 
> Viel Erfolg
> 
> Falls Jemand Empfehlungen für ein stabiles und kompatibles Backend hat würde ich mich freuen. Ich teste aktuell über pump. Da gibt es aber ab und an Fehler beim Beenden des Ladevorgangs.

Ich habe es so versucht, aber es funktioniert bei mir nicht. Der Bootloader akzeptiert keine andere Firmware als BE. Welche BE-Firmware und welchen Bootloader hattest du vor der Installation? Ich habe diese hier: Bootloader-Version: B-3.05c

**Comment by kuehnelfred-cyber** [comment]
@vannilla1 Ich habe die Bootloader-Version 1.03 und hatte die FW: BE-03.01.29 . Deine B-3.05 klingt als wäre diese schon von Compleo gebranded.
Hast du es schon über den STM32 programmer probiert? Ich habe aber von einem User aus dem GoingElectric Forum gehört, dass er damit wohl den Bootloader umgehen kann.  Leider kenne ich mich damit nicht aus. Ich habe nur ein Bild für die richtige PIN-Belegung.
