### ISSUE TITLE
API: enable/disable threshold

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#298]
https://github.com/evcc-io/evcc/pull/6081

in dem Zusammenhang FAQ: Wintermodus anpassen

**Comment by StefanSchoof** [comment]
Vielleicht auch https://github.com/evcc-io/docs/pull/272 noch mal wieder reverten

**Comment by tobiasbayer** [comment]
Dann müsste aber dort noch ein `/` zwischen `enable|disable` und `threshold`. Die Pfade waren im anderen PR leicht anders.
