### ISSUE TITLE
loadpoint prioritisation

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#313]
https://github.com/evcc-io/evcc/pull/6107

**Comment by VolkerK62** [comment]
Ist optional.
Kommt in den Loadpoint und bekommt eine Zahl. `Priority: 2`
Loadpoint mit der höchste Zahl hat die höchste Priorität und bekommt so viel wie möglich von der Ladeleistung eines niedriger priorisierten Laodpoint zugewiesen. Dies führt u. U. kurzfristig zu Netzbezug, bis die Regelung ausnivelliert ist.
Loadpoints ohne Eintrag haben `Priority: 0`.
Wirkt in den Modi `pv` und `minpv`, wobei `minpv` nicht abgebrochen, sondern nur auf minimum reduziert wird.

**Comment by andig** [comment]
Perfekt!
