### ISSUE TITLE
Zählervorzeichen dokumentieren

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#317]
Siehe https://github.com/evcc-io/evcc/issues/6138#issuecomment-1423785038

- Positiv: Erzeugung, Batterieentladung, Hausverbrauch, Netzbezug, Fahrzeugladung.
- Negativ: Einspeisung, Batterieladung(, WR-Eigenverbrauch)

**Comment by VolkerK62** [comment]
ist doch drin .... https://docs.evcc.io/docs/reference/configuration/meters
`evcc benutzt positive (+) Werte für eingehende Ströme (Netzbezug, PV Erzeugung, Hausbatterie-Entladung) und negative (-) Werte für ausgehende Ströme (Netzeinspeisung, PV Wechselrichter Ruhestrombedarf oder Hausbatterie-Ladung). Jeder anderweitiger Strombedarf, inklusive der Wallbox, ist immer ein positiver (+) Wert.`

**Comment by premultiply** [comment]
Ja, passt schon.
