### ISSUE TITLE
"new" cheap 

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#326]
Cheap gibts nicht mehr. Stattdessen kannst Du die Ladeplanung verwenden, siehe https://github.com/evcc-io/evcc/discussions/5639. Zur Prüfung des Tarifes:

    evcc tariff

_Originally posted by @andig in https://github.com/evcc-io/evcc/discussions/6398#discussioncomment-5092817_

**Comment by VolkerK62** [comment]
@andig `cheap` kann ersatzlos gestrichen werden?

- https://docs.evcc.io/docs/reference/configuration/tariffs
- https://github.com/evcc-io/evcc/blob/master/evcc.dist.yaml

**Comment by andig** [comment]
Siehe https://github.com/evcc-io/evcc/discussions/6398#discussioncomment-5098187, aktuell gibts das nicht- ggf. würde es zurück kommen. Die https://github.com/evcc-io/evcc/blob/master/evcc.dist.yaml korrigiere ich, da muss `cheap` aktuell raus. Danke für den Hinweis!

**Comment by VolkerK62** [comment]
https://github.com/evcc-io/evcc/issues/6708

**Comment by VolkerK62** [comment]
https://github.com/evcc-io/evcc/issues/6708

**Comment by VolkerK62** [comment]
Parameter `smartCostLimit` in `site`.
- EUR (Tarif)
- % ??? (Grünstrom)
- gCO2

**Comment by VolkerK62** [comment]
MQTT in API Doku ergänzen
https://github.com/evcc-io/evcc/pull/6971

**Comment by VolkerK62** [comment]
@andig 
Wenn ich es richtig verstanden habe, dass ist es eine entweder/oder Entscheidung.
Entweder ich nutze `tariffs` (Zonen- oder variabel) oder ich nutze `planner` (z.B. GSI)  
Wenn ich einen variablen Tarif konfiguriert habe gebe ich bei `smartCostLimit` einen Preis an (analog wie früher bei cheap).
Habe ich einen fixen Tarif und z.B. GSI konfiguriert, gebe ich ein gCO2equivalent an.
Dazu noch eine Frage: auf "gruenstromindex.de" bekomme ich den %ualen Anteil grünen Stroms angezeigt (z.B. 81%).
Den kann ich hier aber nicht angeben, sondern nur gCO2. Wo kommt das her? Woher weiß ich, wieviel gut oder schlecht ist?

**Comment by andig** [comment]
> Wenn ich es richtig verstanden habe, dass ist es eine entweder/oder Entscheidung.

Ne, das ist falsch.

Der Planner nutzt immer die Tarife. Man kann aber fürs Planen einen anderen (den "planner") Tarif nutzen als für den Netzbezug. Ladekosten nutzen immer "grid", der Planner nutzt "planner" oder "grid".

> sondern nur gCO2. Wo kommt das her? Woher weiß ich, wieviel gut oder schlecht ist?

Aus dem GSI Api. Weniger ist besser- irgendwann musst Du ja laden...
