### ISSUE TITLE
Erklärung RFC 3339

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#335]
@naltatis oder @andig 
https://docs.evcc.io/docs/reference/api
`POST /api/loadpoints/<id>/target/time/<time>: target time in RFC3339 / ISO format`

Ich glaube, die wenigsten wissen, in welcher Form hier Datum und Uhrzeit einzutragen sind.
Ich gehöre dazu ;-)

Hier wäre ein Info-Feld ganz nützlich.

Wäre `2023-02-28T07:30:00` oder `2023-02-28_07:30:00` richtig?
Ist das dann UTC? Muss dann noch ein `+01:00` dahinter?
Muss das in " " gepackt werden?
Geht da auch nur Uhrzeit, ohne Datum? ist das dann täglich?

**Comment by andig** [comment]
https://www.rfc-editor.org/rfc/rfc3339, keine Anführungszeichen

**Comment by VolkerK62** [comment]
Die Seite hatte ich auch schon entdeckt ;-)
Sorry, dass ich nochmal nachfrage (in dem Thema bin ich ein DAU)

Also ist 28.2.2023 um 17:30 Uhr Ortszeit in Deutschland = `2023-02-28T17:30:00+01:00` (und im Sommer dann `+02:00`)

Es muss Datum & Uhrzeit sein?
Nur eine Uhrzeit geht nicht?

**Comment by VolkerK62** [comment]
@andig gibst du mit bitte noch einen kurzen hint, damit ich keinen Müll in die Doku schreibe

**Comment by VolkerK62** [comment]
Ich habe einfach mal try&error gemacht. Die Uhrzeit muss in UTC (`Z`) angegeben werden. Ein `+01:00` am Ende gibt immer ein "404 page not found" aus.

**Comment by premultiply** [comment]
Könnte auch daran liegen dass ein + oder auch : in einer URL ggf. ein Sonderzeichen ist.

Schon vorab urlencode() probiert?

**Comment by VolkerK62** [comment]
urlencode???  Du setzt wieder zu viel Wissen voraus ;-)

```
result:
2023-03-05T07%3A00%3A00%2B01%3A00
 your call:
$returnValue = urlencode('2023-03-05T07:00:00+01:00');
```

**Comment by premultiply** [comment]
🤓🤖👌

**Comment by VolkerK62** [comment]
Jetzt lass mich nicht verhungern.  Was sagt mir das "result" jetzt?

**Comment by VolkerK62** [comment]
kommt auch wieder (erwartbar?) 404
Also muss targettime in UTC angegeben werden, da das `+` wohl das Problem ist

**Comment by premultiply** [comment]
Ja ok, schade.
Einen Versuch war's aber wert und du weisst jetzt was urlencode() macht ;)

**Comment by VolkerK62** [comment]
ok. Dann ist der PR richtig.
