### ISSUE TITLE
Sponsoring für Zaptec Go nicht dokumentiert

### ISSUE THREAD

**Issue by Sillium007** [evcc-io/docs#374]
Siehe Diskussion hier:
https://github.com/evcc-io/evcc/discussions/7579

Die Zaptec Go braucht Sponsering, das ist aber nicht in der Doku beschrieben.

**Comment by VolkerK62** [comment]
ist durch https://github.com/evcc-io/evcc/pull/7592  gefixt worden

**Comment by Sillium007** [comment]
Fixed
