### ISSUE TITLE
mark modbus proxy as sponsorship feature

### ISSUE THREAD

**Issue by kagehisa** [evcc-io/docs#383]
According to the code and the last time I tested the modbus proxy in my evcc config it required a sponsorship token. It would be nice to mark it as such on the config reference page for the modbus proxy.

**Comment by VolkerK62** [comment]
@andig  ist das so?  Immer, oder nur i.V.m. Wallboxen für die Sponsorship notwendig ist?

**Comment by andig** [comment]
Ja, der Proxy erfordert das :/
