### ISSUE TITLE
Custom vehicle cache is deprecated

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#42]
Only soc is actually required

**Comment by DerAndereAndi** [comment]
What do you mean by `soc` is required? Vehicles do have `minSoC` and `targetSoC` options as far as I can see it

**Comment by DerAndereAndi** [comment]
`vehicle cache` being deprecated, meaning we still read the value but don't use it any more?

**Comment by andig** [comment]
Der Parameter „charge“ heisst jetzt „soc“. „Cache“ gibts nicht mehr.

**Comment by andig** [comment]
> `vehicle cache` being deprecated, meaning we still read the value but don't use it any more?

Genau, Warnung im Log

**Comment by DerAndereAndi** [comment]
Fixes
