### ISSUE TITLE
Epic: Restructuring

### ISSUE THREAD

**Issue by naltatis** [evcc-io/docs#450]
From Slack: https://evccgroup.slack.com/archives/C01321PUJAD/p1694874082015199

@markusjnagel wrote:
> So,  - schaut aml hier rein, ob Ihr das so gebrauchen mögt. Ich habe noch keinen PR gestellt, kann ich aber gern machen - baut es erstmal lokal und schaut's euch an.
Die externen Links auf die Doku sollten weiterhin funktionieren (-> auf /docs/Home - aber da ist jetzt erstmal eine generelle Einführung in das Thema).
https://github.com/markusjnagel/evcc-io-docs/tree/refactor_docs

@naltatis wrote
> Hi @Markus Nagel, hatte jetzt mal Zeit, mich mit deinem Vorschlag auseinanderzusetzen. Generell geht das, glaube ich, in die richtige Richtung. Das mehr bebilderte (Screenshots und so) ist gut, da müssen wir mit zunehmendem Abbau der evcc.yaml sowieso hin. Bei der Seite "Die UI" ist mMn zu viel auf einmal drin und die ist auch nicht trennscharf zu "Die Lademodi". Glaube eher, dass wir hier anfangen müssen, in "Funktionen" zu strukturieren. Also "Ladepunkt", "Lademodus", "Ladeplanung", "Stromtarife", "PV-Laden", "Fahrzeuge", "Batterie", "Ladevorgänge", "Energiedaten". Das wären für mich alles einzelne Seiten, auf denen wir die Konzepte erklären - so wie du es mit "Die Lademodi" schon angefangen hast. Momentan sind die Infos dazu etwas verstreut (FAQ, Referenz, ...). Auf Referenz sollten wir von den Funktionsseiten aus gerne verlinken. Aber die Grundprinzipienerklärung sollte mMn. nicht in Referenz (wie heute) stattfinden. Eine FAQ Seite könnten wir gerne behalten, aber nicht als eigene Kategorie mit Unterseiten, sondern wirklich nur als Sammelseite für allgemeine Fragen, die sich keiner Funktion zuordnen lassen können.
Die Idee von der neuen Startseite, die erstmal erklärt worum es eigentlich geht, finde ich gut. Würde das aber vmtl. nicht als eigene Seite sehen. "Überschussladen - was ist das" erklärt das Grundprinzip, beschreibt aber auch schon evcc konkret ist und macht und ist damit ähnlich zur "Einführung in evcc" Seite.
Spannende Frage ist nun wie wir von hier weiter kommen. Ich würde vorschlagen, dass wir im `docs` Repo einen Issue für die Neustrukturierung anlege, in dem wir die neue Struktur (erst mal nur Seiten und grobe Inhalte) mal skizzieren können. Wenn wir da Einigkeit haben, können wir konkret mit PRs arbeiten.
>
> As I'm writing this ... we should do the discussion in the docs issue in English. While doing the english translation @duck. and @j3ff also had restructuring ideas that we'd shelved for later. I think this is a good time to discuss.

**Comment by markusjnagel** [comment]
:+1: 

How do you eat an elephant? 
One bite at a time. :wink: 


> I rather think that we need to start structuring in "functions" here. So "charging point", "charging mode", "charge planning", "electricity tariffs", "PV charging", "vehicles", "battery", "charging processes", "energy data". For me, these would all be individual pages on which we explain the concepts - as you have already started with "The charging modes".

Yes, good point. 
I would also suggest that we keep a general introduction (similar to what I did with "Überschussladen - was ist das" / "Surplus charging - what is it") that explains the general principle. I included evcc on that page on purpose: 
I wanted to show how this general principle is applied - by proprietary solutions and how evcc compares to those, but not going into too much detail on evcc (or proprietary solutions, for that matter). 
Train of thought:

1. What is it (and why should I care)?
2. What needs to be measured to apply it?
3. Solutions
 -- Proprietary
 -- evcc

I don't fully get your comment 
> I like the idea of a new start page that first explains what it's all about. But I wouldn't envision it as a separate page.

:thinking: A start page / landing page would be a separate page, wouldn't it?
