### ISSUE TITLE
evcc backup and restore

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#457]
Hallo,

gibt es eine Anleitung wie man ein komplettes Backup vom evcc auf einem Raspberry Pi macht und anschließend auf einem neu installiertem Raspberry Pi wiederherstellen kann? Ich würde gerne alle Daten wie Ladevorgänge usw. auf das neue System übertragen.

Danke für eure Hilfe.

_Originally posted by @Peter54879 in https://github.com/evcc-io/evcc/discussions/10311_

**Comment by VolkerK62** [comment]
yaml kopieren:  `sudo cp /etc/evcc.yaml /home/pi/evcc.yaml.bak`
db kopieren: `sudo cp /var/lib/evcc/evcc.db /home/pi/evcc.db.bak

**Comment by Peter54879** [comment]
Das Backup hat funktioniert.
Leider bekomme ich die .db nicht auf den neuen Raspberry Pi überschrieben.

**Comment by Marty56** [comment]
Ein Kopie eine laufenden SQL Datenbank ist u.U. korrupt.
Normalerweise nimmt man dazu ein Backup Mechanismus der DB

**Comment by Aitschcux** [comment]
Hallo!
Wie könnte ich denn eine evcc.db.bak, welche ich zuvor von meinem alten Raspberry Pi auf meinen Mac gesichert habe, z. B. per ssh auf meinen neu installierten Raspberry Pi zurück kopieren? Hier würde ich mich freuen, wenn die Doku bzgl. des o. g. Beispiels noch ergänzt werden könnte. Besten Dank im Voraus und vielen Dank für Eure Hilfe!

**Comment by VolkerK62** [comment]
Im Prinzip, wie in der Doku beschrieben, nur Speicherort/name und Zielort/name tauschen

hin:  `sudo cp /var/lib/evcc/evcc.db /home/pi/evcc.db.bak`

zurück:  `sudo cp /home/pi/evcc.db.bak /var/lib/evcc/evcc.db`
