### ISSUE TITLE
add `batteryDiscargeControl` to site

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#471]
https://github.com/evcc-io/evcc/issues/10379#issuecomment-1806772578

**Comment by VolkerK62** [comment]
und API erweitern
https://github.com/evcc-io/evcc/pull/10815#issuecomment-1818859798

**Comment by PeterPablo** [comment]
`minsoc` und `maxsoc` für mindestens SofarSolar erläutern, vgl. https://github.com/evcc-io/evcc/pull/10847

**Comment by VolkerK62** [comment]
>minsoc und maxsoc für mindestens SofarSolar erläutern, vgl. https://github.com/evcc-io/evcc/pull/10847

das ist dann mMn eher etwas für das Geräte-Template und nicht für die "globale" Einstellung
