### ISSUE TITLE
tariff: EDF tempo

### ISSUE THREAD

**Issue by VolkerK62** [evcc-io/docs#504]
https://github.com/evcc-io/evcc/pull/11051

**Comment by VolkerK62** [comment]
@andig 
hier blick ich bei der Configuration noch nicht durch
Ist das https://github.com/evcc-io/evcc/issues/11040#issuecomment-1850671202  jetzt schon umgesetzt?
So wie ich das interpretiere, ist das in #11051 nicht drin.
Ist die aktuelle Implementierung eigentlich nutzbar?

**Comment by andig** [comment]
Der funktioniert noch nicht- kanst du erstmal ignorieren :/
