### ISSUE TITLE
Nachrichtendoku für ${loadpoint} falsch

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#51]
https://docs.evcc.io/docs/reference/configuration/messaging/
Mögliche Variablen:
**${loadpoint}: Text mit dem Wert von title des loadpoints (Ladepunkt)**
${mode}: Text mit dem aktiven Lademodus
${energy:%.1f}: Geladene Energiemenge in kWh
${duration}: Dauer der Ladezeit

Logfile mit fritzdect mache ich bis morgen

_Originally posted by @hrpv in https://github.com/evcc-io/evcc/discussions/2381#discussioncomment-2027198_

**Comment by andig** [comment]
Siehe auch https://github.com/evcc-io/evcc/pull/2383

**Comment by DerAndereAndi** [comment]
Fix kommt mit https://github.com/evcc-io/docs/pull/55

**Comment by DerAndereAndi** [comment]
Ist gemerged und deployed
