### ISSUE TITLE
SimpleEVSE missing modbus id

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#52]
https://docs.evcc.io/docs/devices/chargers/#simple-evse

<img width="713" alt="Screenshot 2022-01-23 at 14 39 01" src="https://user-images.githubusercontent.com/184815/150681206-75a0eaec-7d9d-4be2-af89-c0833b99724e.png">

**Comment by RTTTC** [comment]
This controller in is also named incorrectly, (Simple EVSE has no RS485)
Appropriate name is EVSE DIN
Source - developer:
http://evracing.cz/simple-evse-wallbox

**Comment by DerAndereAndi** [comment]
Fixed via https://github.com/evcc-io/config/commit/005033049f9d85ce0ac98f16d0987b602a098a00

Will be populated automatically after successful build.
