### ISSUE TITLE
Add usage=aux to meters page

### ISSUE THREAD

**Issue by naltatis** [evcc-io/docs#520]
Add new aux type to https://docs.evcc.io/docs/devices/meters

**Comment by premultiply** [comment]
Hier haben wir noch generell ein bisschen das kosmetische Problem dass Geräte abhängig von ihrer usage (teilweise auch mehrfach) in brands.json und damit auf der Webseite bei den Herstellern der Gerätekategorien auftauchen.

Das führt machmal zu lustigen Effekten wie z. B. dass ein Modbus-Zähler-Hersteller (der ja z. B. auch ein PV-Erzeugungszähler sein kann) dort als Wechselrichterhersteller auftaucht. Gleiches gilt ähnlich für `evcc configure`.

**Comment by andig** [comment]
Es wird langsam dringender- die ersten Configs mit "undefined" tauchen auf: 
![Bildschirmfoto 2024-02-06 um 10 34 59](https://github.com/evcc-io/docs/assets/184815/260d86a0-d09e-478c-ba8a-c8db3f75f3ac)

**Comment by naltatis** [comment]
Doku ist angepasst. Bei `configure` müsste jemand von euch bitte mal reinschauen. Außerdem ist mir der hier aufgefallen:

![Bildschirmfoto 2024-02-06 um 16 31 30](https://github.com/evcc-io/docs/assets/152287/5be4315b-8d9e-4a1b-aaba-9d16970cfd82)

Finde den Beschreibungstext etwas verwirrend. Gerade weil der Inhalt nicht zu den Metadaten (`usage`) passt.
