### ISSUE TITLE
EVSE DIN RS485 is incorrectly named as SimpleEVSE

### ISSUE THREAD

**Issue by RTTTC** [evcc-io/docs#54]
This [charge controller](https://docs.evcc.io/docs/devices/chargers/#simple-evse) is named incorrectly, (Simple EVSE has no RS485)
Appropriate name is EVSE DIN RS485
Source - developer:
http://evracing.cz/simple-evse-wallbox

**Comment by andig** [comment]
Already implemented.

**Comment by andig** [comment]
Actually, keeping open until published.
