### ISSUE TITLE
Meter missing powers

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#568]
this is working well! thanks!
I mean the generic template here: [https://docs.evcc.io/docs/devices/meters#](url)

_Originally posted by @pdonn in https://github.com/evcc-io/evcc/issues/13867#issuecomment-2171804761_

**Comment by VolkerK62** [comment]
zusätzlich zu `powers` fehlt auch noch `voltages`.

Ist das ein Template (hab keins gefunden), oder kann man das direkt in der Doku ändern?

**Comment by premultiply** [comment]
Müsste man direkt in der Doku ändern können, oder @naltatis ?

**Comment by andig** [comment]
Dann sollten wir auch gleich dazu schreiben wofür die jeweils verwendet werden.

- Spannungen: Anschlusserkennung 1p3p
- Ströme: Erkennung aktive Phasen
- Leistungen: Vorzeichenerkennung für Ströme falls diese vorzeichenlos sind
