### ISSUE TITLE
Howto generate logs in UI

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#579]
We need to document the new feature introduced in this PR: https://github.com/evcc-io/evcc/pull/13330

Can replace/ be added to https://docs.evcc.io/docs/faq#wie-kann-ich-ein-logfile-zur-fehleranalyse-erstellen

**Comment by VolkerK62** [comment]
In dem Zusammenhang ....
wäre es machbar bei den Bereichen eine Mehrfachauswahl zu ermöglichen?
So könnte man zB. besonders bei `Trace` einige unnötige Bereiche ausblenden und dadurch das Log lesbarer gestalten.
