### ISSUE TITLE
How is loadpoint to root circuit assignment expected to work?

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#587]
From https://github.com/evcc-io/evcc/issues/14261#issuecomment-2241058306:

> But I I have noticed a difference in behavior and how the documentation describes how it should work. This statement: "Alle Ladepunkte ohne explizite Stromkreiszuordnung werden diesem Hauptstromkreis zugeordnet. " I conclude from this that if I have only one circuit "main" I do not need to specify "circuit" on the loadpoint configuration. But if I try this loadmanagement does not work on mij loadpoints. I need to specify "circuit: main" on the loadpoints and then it works.

Original doku: https://github.com/evcc-io/docs/pull/567

/cc @premultiply wie war der letzte Stand?

**Comment by andig** [comment]
@Roeland54 @naltatis aktuell müssen die Ladepunkte explizit einem Circuit zugeordnet werden. Der Satz in der Doku:

> "Alle Ladepunkte ohne explizite Stromkreiszuordnung werden diesem Hauptstromkreis zugeordnet. "

ist aktuell falsch.

**Comment by naltatis** [comment]
Die Doku ist inzwischen an den aktuellen Softwarestand angepasst.

Jetzt stellt sich nur die Frage, ob das aktuelle Verhalten ein Bug oder ein Feature ist 😄 @premultiply

**Comment by andig** [comment]
Feature!

**Comment by naltatis** [comment]
> Feature!

Dann ist hier nichts mehr zu tun.
