### ISSUE TITLE
Document mincurrent/maxcurrent api

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#59]
...bei Gelegenheit sollten wir mal überlegen, das in "settings" zu ändern.

**Comment by andig** [comment]
`targetcharge` fehlt ebenfalls

**Comment by DerAndereAndi** [comment]
Nein da bin ich anderer Meinung. Das ist eine Referenz, keine Settingsübersicht. Das ist viel zu komplex. Die möglichen Einstellungen werden in Zukunft durch die Templates alle direkt sichtbar beim Template. Das ist sowieso notwendig im irgendwann mal eine UI dafür anbieten zu können.

Das einzige was noch offen ist, sind die Bereich die heute noch nicht über Templates abgedeckt sind, z.b. generell was in Loadpoints, Messaging, etc. pp passiert. Aber da werden wir auch noch hinkommen.

Was in der Referenz klarer machen können, außer fehlendes zu ergänzen, sind die Beispiele ausführliche zu beschreiben, damit man die sich nicht aus der Hierarchie zusammendenken muss.

**Comment by andig** [comment]
Verstehe ich nicht. Ist das ein Grund, bestehende APIs nicht zu dokumentieren?

**Comment by DerAndereAndi** [comment]
Hatte ich missverstanden, dachte es ging um Konfigurationen. Sorry.

**Comment by DerAndereAndi** [comment]
Dann verstehe ich jetzt aber deinen Text in https://github.com/evcc-io/docs/issues/59#issue-1118157650 nicht

**Comment by andig** [comment]
> ..bei Gelegenheit sollten wir mal überlegen, das in "settings" zu ändern.

Ich meinte dass wir ggf. statt 10 apis mal 1 draus machen. Wir könnten uns ein "Dev meeting" Projekt anlegen um solche Themen für die Agenda zu sammeln?
