### ISSUE TITLE
Update token docs

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#60]
Es sollte ein Contributor's & Sponsor's Token, nciht nur "Sponsors".

**Comment by DerAndereAndi** [comment]
Auf was beziehst du dich hier? sponsorship Webseite?

**Comment by DerAndereAndi** [comment]
Schau dir bitte mal den PR an. Habe auch noch etwas erklärt warum wir GitHub dafür verwenden. @naltatis könntest du bitte auch mal drüber schauen?

**Comment by andig** [comment]
Find ich Klasse!
