### ISSUE TITLE
bessere Beschreibung der Parameter für SAJ-H2 aktive Batteriesteuerung

### ISSUE THREAD

**Issue by UDicke** [evcc-io/docs#623]
https://github.com/evcc-io/docs/blame/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/de/meter/saj-h2_1.yaml#L52-L54

Mein Vorschlag für die 3 Zeilen:
de:
      defaultmode: 2 # backup_mode, Wert bitte nicht ändern, erforderlich für die aktive Batteriesteuerung - Laden aus dem Netz
      minsoc: 20 # Notstromkapazität, auf diesen Wert wird der Speicher eingestellt bei "Entladesperre aus" (optional)
      maxsoc: 95 # Notstromkapazität, ab diesem SOC-Wert und kleiner wird die Entladesperre aktiv bei "Entladesperre ein" (optional)

Der Block ist mehrfach vorhanden.
https://github.com/evcc-io/docs/blame/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/de/meter/saj-h2_1.yaml#L102-L104
und
https://github.com/evcc-io/docs/blame/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/de/meter/saj-h2_1.yaml#L153-L155

en:
	  defaultmode: 2 # backup_mode, please do not change the value, required for active battery control - charging from grid
	  minsoc: 20 # emergency power capacity, the system is set to this value when "discharge lock off" (optional)
          maxsoc: 95 # emergency power capacity, from this SOC value and lower, the discharge lock becomes active with "discharge lock on" (optional)

https://github.com/evcc-io/docs/blob/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/en/meter/saj-h2_1.yaml#L52-L54
https://github.com/evcc-io/docs/blob/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/en/meter/saj-h2_1.yaml#L102-L104
https://github.com/evcc-io/docs/blob/470524f3ab786f66ada952a2e791c6b189e62e6f/templates/release/en/meter/saj-h2_1.yaml#L153-L155

Gleiches gilt natürlich auch für die saj-h2_0.yaml in "de" und "en". Ich habe gerade erst kapiert wieso da 2 Dateien sind...

@andig, ich hoffe das Verfahren für diesen Vorschlag ist richtig. Ich als Anfänger finde es nicht leicht den richtigen Weg zu finden. 😊
Und danke nochmal für die Anpassungen. Funktioniert alles wie es soll!

**Comment by andig** [comment]
Du musst bitte einfach in das "normal" evcc repo gehen und da die Datei wie gewünscht editieren. Die Doku wird daraus automatisch erzeugt.

**Comment by UDicke** [comment]
Es tut mir leid, ich bin leider wieder überfordert,
in https://github.com/evcc-io/evcc finde ich keine saj-h2_0.yaml oder was meinst Du mit 'das "normal" evcc repo '?

![grafik](https://github.com/user-attachments/assets/a41e0f35-89c9-4942-a5d6-6c8e4ea57eda)
In der Doku finde ich die Quelldateien, finde aber nicht wie ich die editieren kann und vorschlagen kann.
Kannst Du mir nochmal helfen bitte oder einen Hinweis geben welche Anleitung ich studieren muss?

**Comment by andig** [comment]
https://github.com/evcc-io/evcc/blob/master/templates/definition/meter/saj-h2.yaml

Branch kannst Du links auswählen.

**Comment by UDicke** [comment]
Danke, aber da bin ich doch im quasi im Programmcode und nicht in der Doku. Verstehe ich nicht...
Oder finde ich da den Link zur Doku nicht!?
Ich habe jetzt das gemacht:
https://github.com/evcc-io/docs/compare/main...UDicke:docs:patch-1
geht der Rest jetzt automatisch oder muss ich noch einen "create pull request" auslösen?
Oder ist die Stelle doch falsch?


![grafik](https://github.com/user-attachments/assets/00c57920-698d-4261-b8fc-2c8622832db6)

**Comment by andig** [comment]
Das _ist_ die Doku. Die wird nämlich daraus generiert.

**Comment by UDicke** [comment]
Also hab ich das jetzt richtig gemacht? Muss ich noch was tun, z.B. "Create pull request"?

**Comment by andig** [comment]
Du musst einen PR für genau die Datei im anderen Repository machen. NICHT hier.

**Comment by UDicke** [comment]
@andig tut mir echt leid, ich verstehe Deine Kommentare und Erklärungen nicht. ☹
Was heist 
> Du musst einen PR für genau die Datei im anderen Repository machen. NICHT hier.

?
Wenn ich lese wie ich einen Beitrag zur Doku leisten kann, verstehe ich das so unnd das ist mein Ergebnis:
https://github.com/evcc-io/docs/pull/624
Ich hoffe, dass es dort in evcc-io/docs jemand freigibt...

**Comment by andig** [comment]
Der PR muss in der yaml Datei gemacht werden. Und die liegt nicht im docs Repository.

**Comment by UDicke** [comment]
Die Zeilen zum Erzeugen der Einträge in der Doku finde ich da aber nicht. Wie entsteht dann die Doku?

**Comment by andig** [comment]
Ich habs dir oben schonmal verlinkt…

**Comment by UDicke** [comment]
[templates/definition/meter/saj-h2.yaml](templates/definition/meter/saj-h2.yaml) finde ich und fand die auch vorher. Leider sehe und verstehe ich den Zusammenhang mit der Doku nicht.

**Comment by andig** [comment]
Das _ist_ die Doku.

**Comment by UDicke** [comment]
https://github.com/evcc-io/evcc/blob/master/templates/definition/meter/saj-h2.yaml ?

und wo finde ich da
![grafik](https://github.com/user-attachments/assets/2efe4158-6b0c-448a-9885-1b7e6077ed32)
um eine Änderung vorzuschlagen?

**Comment by andig** [comment]
Da wo allgemein gültige Parameter definiert sind: defaults.yaml

**Comment by UDicke** [comment]
ok, hab ich gefunden
https://github.com/evcc-io/evcc/blob/master/util/templates/defaults.yaml

kann ich dann für diesen Fall description: und help: in der saj-h2.yaml etwa so ergänzen, die doku übernimmt das und nimmt nicht mehr den default?

```
- name: minsoc
    description:
      de: Notstromkapazität in % im Backup Mode (normaler Betriebsmodus)
      en: emergency power capacity in % in Backup Mode (normal working mode)
    help:
      de: Notstromkapazität, auf diesen Wert wird der Speicher eingestellt bei "Entladesperre aus" bzw. "Entladesperre nicht aktiv"
      en: emergency power capacity, the system is set to this value when "discharge lock off" or "discharge lock not active"**_
    type: number
    default: 20
    advanced: true
```

**Comment by andig** [comment]
Das machst Du indem Du die gewünschten Übersteuerungen im SAJ Template bei den Parametern ergänzt.

**Comment by UDicke** [comment]
@andig , danke für Deine Geduld. Für einen absoluten Neuling ist das eben nicht so einfach...
Ich hoffe ich habe jetzt verstanden und den richtigen Weg gewählt! 😊

https://github.com/evcc-io/evcc/pull/16356
