### ISSUE TITLE
Leistungslose Smartplugs

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#64]
Im Template zu TPLink steht:

    treat as charging above this power

Bei FritzDECT haben wir angefangen, Werte <0 für leistungsloses Schalten zu verwenden, die `standbypower` verliert also ihre Bedeutung.

**Comment by DerAndereAndi** [comment]
Das sollte durch https://github.com/evcc-io/docs/pull/67 abgehandelt sein, sobald das gemerged wird.

**Comment by thierolm** [comment]
Hab' in meinem https://github.com/evcc-io/evcc/pull/3311 PR, aus den charger templates den Kommentar oben entfernt. In der Doku wird das Verhalten beschrieben.

**Comment by andig** [comment]
Top, danke!
