### ISSUE TITLE
Document: Add MaxACPower hybrid battery setting

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#641]
We need to document the new feature introduced in this PR: https://github.com/evcc-io/evcc/pull/16609

**Comment by naltatis** [comment]
Short descriptions is available at all hybrid inverters with this setting.
Features was described in the last blogpost https://docs.evcc.io/blog/2024/11/22/highlights-charts-stats#hybridwechselrichter-mit-beschränkter-ac-leistung
