### ISSUE TITLE
Document HA

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#642]
Add something like:

While Homeassistent has some great features and supports running evcc, some capabilities are not available:

- access to evcc nightly releases
- running the command line tools (evcc meter|charger|tariff etc.)

If any of there are important for you, you'll need to install evcc outside of Homeassistent.

**Comment by naltatis** [comment]
fixed with https://github.com/evcc-io/docs/commit/c6f059e4a7f812c35de8a37a26732cb97454b8f7
