### ISSUE TITLE
Document movingaverage meter

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#81]
Ne, ich meine das https://github.com/evcc-io/evcc/blob/master/meter/meter_average.go. Das kannst Du um einen anderen Zähler wrappen, allerdings wird nur Leistung mit Durchschnitt bewertet, nicht die anderen Parameter.

_Originally posted by @andig in https://github.com/evcc-io/evcc/discussions/2665#discussioncomment-2323368_

**Comment by VolkerK62** [comment]
@andig  da würd ich mich mal an eine Beschreibung wagen, allerdings ist mir die Funktionalität noch nicht so ganz klar. 
Ich habe mal versucht, den Code zu lesen (absolutes Neuland).
Wenn ich es richtig verstanden habe, wird der aktuell gemessene Wert (value) mit `decay` und der vorherige Mittelwert? (m.value) mit `1-decay` multipliziert. Das ist dann der neue Mittelwert für die nächste Berechnung.

**Comment by VolkerK62** [comment]
und noch eine Frage: Wo kann man das einsetzen? Nur bei `meter` vermute ich. Also bei `grid` `pv` `battery`? Bei `charge` dürfte es keinen Sinn machen.

**Comment by andig** [comment]
Wenn Du suchst findest Du einen Anwendungsfall fürs `grid` Meter- jemand hatte eine stark pulsende Kaffeemaschine ;)

**Comment by VolkerK62** [comment]
Der Tipp war gut. 
Ich würde es dann hier einbauen: https://docs.evcc.io/docs/reference/configuration/meters#unterst%C3%BCtzte-typen
Oder hast du einen besseren Ort?
