### ISSUE TITLE
Daheimladen: Document Firmware requirement

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#84]
Ok, I will trust the experienced
@utsavanand2  pls change the firmware

_Originally posted by @VolkerK62 in https://github.com/evcc-io/evcc/discussions/2784#discussioncomment-2323927_

**Comment by utsavanand2** [comment]
Thanks a lot @andig for the issue documenting the requirement :)

**Comment by andig** [comment]
Done as part of the template
