### ISSUE TITLE
Grundlegende Konfiguration

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#91]
https://docs.evcc.io/docs/guides/setup fehlt eine Beschreibung der grundlegenden Konfiguration sowie ein Verweis auf 

    evcc configure

(Ladepunkt, insbesondere auch https://github.com/evcc-io/evcc/discussions/2946#discussioncomment-2407079. Stattdessen wird die Ersparnisanzeige beschrieben.

**Comment by VolkerK62** [comment]
Ich denke dieses issue kann geschlossen werden.
Der Punkt "Setup" ist jetzt anders gestaltet und `evcc configure` ist mittlerweile unter "Erste Schritte (overview) aufgeführt.

**Comment by andig** [comment]
Klasse, vielen Dank!
