### ISSUE TITLE
Document plugin capabilities, e.g. regex

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#95]
> Wie kann ich das Filtern? 

Indem Du kein W mit schickst ;) Alternativ gibts ein `regex` Setting das in der Lage sein sollte, das trailing W rauszufiltern.

_Originally posted by @andig in https://github.com/evcc-io/evcc/discussions/3073#discussioncomment-2497981_

**Comment by premultiply** [comment]
Duplicate of #80
