### ISSUE TITLE
Add Docker FAQ regarding overwriting /etc

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#96]
See https://github.com/evcc-io/evcc/issues/3089

**Comment by premultiply** [comment]
Eigentlich steht das doch hier https://docs.evcc.io/docs/installation/docker/#manuell schon:
![grafik](https://user-images.githubusercontent.com/4681172/162285585-8a99a6a0-4f94-46b2-af01-02c4a9eb2c2f.png)

Und in in den `docker run`-Beispielen wird das auch nirgends gemacht.

Was tun?

**Comment by andig** [comment]
Erledigt. Danke für den Hinweis!

**Comment by andig** [comment]
Das docker-compose Beispiel ist allerdings ziemlich sinnlos und overengineered, v.a. Da wir nichts „composen“.  Das wär schick mit influx und grafana.

**Comment by premultiply** [comment]
Gerne ein PR. Ich hab davon Null Plan.
