### ISSUE TITLE
Describe phase timer

### ISSUE THREAD

**Issue by andig** [evcc-io/docs#99]
Achso, danke.
Laut der Beschreibung in https://docs.evcc.io/docs/reference/configuration/loadpoints bin ich davon ausgegangen, dass diese beiden Werte nur das Starten und Stoppen eines Ladevorgangs beeinflussen und nicht die Phasenumschaltung.

Vielen Dank

_Originally posted by @MrJoki007 in https://github.com/evcc-io/evcc/discussions/3139#discussioncomment-2544370_

**Comment by VolkerK62** [comment]
see #125

**Comment by VolkerK62** [comment]
@andig  #125 ist drin. Dann kann dieses issue doch geschlossen werden, oder?
